/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalystsRouteImport } from './routes/catalysts'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as LiteratureRouteImport } from './routes/literature'
import { Route as ModelRouteImport } from './routes/model'
import { Route as RequestRouteImport } from './routes/request'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalystsRoute = CatalystsRouteImport.update({
  id: '/catalysts',
  path: '/catalysts',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteratureRoute = LiteratureRouteImport.update({
  id: '/literature',
  path: '/literature',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalysts': typeof CatalystsRoute
  '/database': typeof DatabaseRoute
  '/literature': typeof LiteratureRoute
  '/model': typeof ModelRoute
  '/request': typeof RequestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalysts': typeof CatalystsRoute
  '/database': typeof DatabaseRoute
  '/literature': typeof LiteratureRoute
  '/model': typeof ModelRoute
  '/request': typeof RequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalysts': typeof CatalystsRoute
  '/database': typeof DatabaseRoute
  '/literature': typeof LiteratureRoute
  '/model': typeof ModelRoute
  '/request': typeof RequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/catalysts' | '/database' | '/literature' | '/model' | '/request'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalysts' | '/database' | '/literature' | '/model' | '/request'
  id:
    | '__root__'
    | '/'
    | '/catalysts'
    | '/database'
    | '/literature'
    | '/model'
    | '/request'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalystsRoute: typeof CatalystsRoute
  DatabaseRoute: typeof DatabaseRoute
  LiteratureRoute: typeof LiteratureRoute
  ModelRoute: typeof ModelRoute
  RequestRoute: typeof RequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalysts': {
      id: '/catalysts'
      path: '/catalysts'
      fullPath: '/catalysts'
      preLoaderRoute: typeof CatalystsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literature': {
      id: '/literature'
      path: '/literature'
      fullPath: '/literature'
      preLoaderRoute: typeof LiteratureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalystsRoute: CatalystsRoute,
  DatabaseRoute: DatabaseRoute,
  LiteratureRoute: LiteratureRoute,
  ModelRoute: ModelRoute,
  RequestRoute: RequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
